// <auto-generated />
using System;
using AutoServis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoServis.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702004703_UpdateVehiclePlateNumber")]
    partial class UpdateVehiclePlateNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AutoServis.Api.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("AutoServis.Api.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Includes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Održavanje",
                            Description = "Zamena ulja, filtera ulja i osnovna provera vozila.",
                            Duration = 60,
                            Includes = "Zamena motornog ulja|Zamena filtera ulja|Provera tečnosti|Vizuelni pregled vozila",
                            Name = "Mali servis",
                            Price = 7500m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Održavanje",
                            Description = "Detaljan servis vozila koji obuhvata zamenu ključnih potrošnih delova.",
                            Duration = 180,
                            Includes = "Zamena zupčastog kaiša|Zamena španera|Zamena vodene pumpe|Kontrola sistema hlađenja",
                            Name = "Veliki servis",
                            Price = 28000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Dijagnostika",
                            Description = "Računarska dijagnostika i očitavanje grešaka na vozilu.",
                            Duration = 45,
                            Includes = "Očitavanje grešaka|Analiza parametara|Brisanje grešaka|Preporuka za popravku",
                            Name = "Dijagnostika vozila",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Popravka",
                            Description = "Pregled i zamena kočionih pločica ili diskova po potrebi.",
                            Duration = 90,
                            Includes = "Pregled kočionog sistema|Zamena pločica|Kontrola diskova|Test kočenja",
                            Name = "Zamena kočnica",
                            Price = 12000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Registracija",
                            Description = "Provera osnovne ispravnosti vozila pre tehničkog pregleda.",
                            Duration = 60,
                            Includes = "Provera svetlosne signalizacije|Provera kočnica|Provera pneumatika|Provera osnovne dokumentacije",
                            Name = "Priprema za tehnički pregled",
                            Price = 5000m
                        });
                });

            modelBuilder.Entity("AutoServis.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AutoServis.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AutoServis.Api.Models.Appointment", b =>
                {
                    b.HasOne("AutoServis.Api.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoServis.Api.Models.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoServis.Api.Models.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoServis.Api.Models.Vehicle", b =>
                {
                    b.HasOne("AutoServis.Api.Models.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoServis.Api.Models.Service", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AutoServis.Api.Models.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AutoServis.Api.Models.Vehicle", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
